parameters:
  minishlink_web_push.class: Minishlink\WebPush\WebPush

services:
  minishlink_web_push:
    class: '%minishlink_web_push.class%'
    arguments: ['%minishlink_web_push.auth%', '%minishlink_web_push.default_options%', '%minishlink_web_push.timeout%', null]
    calls:
      - [setAutomaticPadding, ['%minishlink_web_push.automatic_padding%']]
